from pathlib import Path
from html import escape
from urllib.parse import quote

root = Path(__file__).parent / 'dist'
nav = [('Home','/'),('Our Story','/about/'),('Offerings','/offerings/'),('Shop','/shop/'),('Contact','/contact/')]
products = [
 ('cacao-hape','Cacao Hapé','Hapé','Warm · Heart-centered · Gentle','Cacao Hapé carries a warm, nurturing quality that invites you inward. Traditionally associated with the heart, cacao complements Hapé with a softer, more expansive energy—beautiful for meditation, emotional reflection, prayer, and moments when you want to reconnect with yourself from a place of openness.'),
 ('murici-hape','Murici Hapé','Hapé','Grounding · Clearing · Protective','Murici is a deeply grounding Hapé traditionally prepared using the Murici tree. Its energy is often described as steady, cleansing, and centering—supporting moments of release while bringing awareness back into the body. A beautiful medicine for clearing heaviness, grounding your energy, and returning to center.'),
 ('samauma-flower-hape','Samaúma Flower Hapé','Hapé','Expansive · Uplifting · Prayerful','Known as the Mother of Trees, the great Samaúma is one of the towering beings of the Amazon rainforest. This flower blend carries a lighter, more expansive quality—inviting openness of the heart, prayer, meditation, and connection to something greater than ourselves. Rooted yet spacious, Samaúma Flower is medicine for opening upward while remaining connected to the Earth.'),
 ('kuripe','Kuripe','Applicator','For self-application','A Kuripe is a traditional V-shaped applicator used to serve Hapé to yourself. Connecting the mouth to the nostril, it allows the medicine to be received through your own breath and intention. More than simply a tool, the Kuripe can become a personal ceremonial object—an extension of your relationship with the medicine and your individual practice.'),
 ('tepi','Tepi','Applicator','For serving another','A Tepi is a longer ceremonial applicator used to serve Hapé from one person to another. Traditionally used within shared or guided practice, the Tepi brings relationship, trust, intention, and responsibility into the serving of the medicine. It is a tool for those called to hold space and work with Hapé in community or ceremony.')
]

def shell(title, body, active='', description='Sacred Origins NYC — community, ceremony, and thoughtfully selected botanical tools.'):
    links=''.join(f'<a href="{href}" class="{"active" if active==label else ""}">{label}</a>' for label,href in nav)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#183126"><title>{escape(title)} | Sacred Origins NYC</title><meta name="description" content="{escape(description,quote=True)}"><link rel="icon" href="/assets/sacred-origins-logo.png" type="image/png"><link rel="apple-touch-icon" href="/assets/sacred-origins-logo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Manrope:wght@400;500;600&family=Playfair+Display:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/style.css"><link rel="stylesheet" href="/assets/theme.css"><script defer src="/assets/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><div class="announcement"><span class="announcement-left">NYC · A PLACE TO RETURN TO</span><span class="announcement-center">ROOTED IN COMMUNITY · GUIDED BY INTENTION</span><span class="announcement-right">EST. IN CONNECTION <span aria-hidden="true">✳</span></span></div><header class="header"><div class="header-inner"><span class="header-loc">SACRED ORIGINS<br>NEW YORK CITY</span><a class="brand" href="/" aria-label="Sacred Origins home"><img class="brand-logo" src="/assets/sacred-origins-logo.png" width="302" height="302" alt="Sacred Origins NYC"></a><div class="header-actions"><a class="header-shop" href="/contact/">LET’S CONNECT <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Open menu" aria-controls="nav" aria-expanded="false"><span></span><span></span></button></div></div><nav class="nav" id="nav" aria-label="Main navigation">{links}</nav></header><main id="main">{body}</main><footer class="footer"><div class="footer-intro"><span class="eyebrow light">THE NEXT CHAPTER BEGINS HERE</span><a href="/contact/">Stay in touch <span aria-hidden="true">↗</span></a></div><div class="footer-top"><div><a class="footer-logo" href="/" aria-label="Sacred Origins home"><img src="/assets/sacred-origins-logo.png" width="302" height="302" alt="Sacred Origins NYC"></a><p>For ritual, reflection<br>and the spaces between.</p><a href="mailto:sacredoriginsnyc@gmail.com" class="footer-mail">sacredoriginsnyc@gmail.com ↗</a></div><div><h3>Explore</h3><a href="/about/">Our Story</a><a href="/offerings/">Offerings</a><a href="/shop/">The Shop</a></div><div><h3>Connect</h3><a href="/contact/">Contact Us</a><span>New York City</span></div></div><a class="footer-wordmark" href="/" aria-label="Sacred Origins home">SACRED<span>✺</span>ORIGINS</a><div class="footer-bottom"><span>© 2026 Sacred Origins NYC</span><span>ROOTED IN COMMUNITY · GUIDED BY INTENTION</span><a href="#main">BACK TO TOP ↑</a></div></footer></body></html>'''

def write(path, content):
    p=root/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(content)

def card(p):
    slug,name,cat,mood,_=p
    return f'''<a class="product-card" href="/shop/{slug}/"><div class="product-image product-{slug}"><span class="image-stamp">SO / 0{products.index(p)+1}</span><span class="product-arrow" aria-hidden="true">↗</span></div><div class="product-meta"><span>{cat}</span><span>Explore ↗</span></div><h3>{name}</h3><p>{mood}</p></a>'''

home='''<section class="hero"><div class="hero-grain"></div><div class="hero-content"><p class="eyebrow light">A SPACE FOR COMING BACK TO YOURSELF <span>— NYC</span></p><h1>Where we<br><em>begin again.</em></h1><p>Rooted in ancestral wisdom. Held by community. An invitation to reconnect with what matters most.</p><div class="hero-buttons"><a class="button button-cream" href="/shop/">Explore the apothecary <span>↗</span></a><a class="text-link light-link" href="/about/">Meet Sacred Origins <span>↗</span></a></div><div class="hero-index">01 <span>/</span> 04 <i></i> DISCOVER THE STORY</div></div><div class="hero-visual"><div class="hero-picture"></div><div class="hero-visual-top">THE ART OF RETURNING <span>✺</span> SACRED ORIGINS</div><div class="hero-visual-bottom"><span>EST. IN CONNECTION</span><span>NEW YORK CITY</span></div></div><div class="hero-vertical">INTENTION · COMMUNITY · ORIGIN · INTENTION · COMMUNITY</div></section>
<section class="ticker" aria-label="Our values"><div>GATHER WITH INTENTION <span>✺</span> RETURN TO ORIGIN <span>✺</span> HONOR THE JOURNEY <span>✺</span> GATHER WITH INTENTION <span>✺</span> RETURN TO ORIGIN <span>✺</span></div></section>
<section class="intro section-wrap reveal"><div class="section-label"><span class="tiny-star">✺</span> 01 / THE ETHOS <span class="line"></span> NEW YORK CITY</div><div class="intro-grid"><div><span class="intro-overline">BEYOND THE EVERYDAY</span><h2>Healing is a<br><em>collective journey.</em></h2></div><div><p>At Sacred Origins NYC, we honor the wisdom and resilience of our ancestors while creating a welcoming space for connection, reflection, and personal growth.</p><p>Our work is rooted in supporting BIPOC communities through intentional practices and experiences that invite us back to ourselves—and to one another.</p><a class="underline-link" href="/about/">The story behind Sacred Origins <span>↗</span></a></div></div></section>
<section class="editorial"><div class="editorial-photo" role="img" aria-label="Botanical apothecary still life"><div class="photo-caption">SO / THE APOTHECARY <span>01—05</span></div></div><div class="editorial-copy"><span class="eyebrow">02 / THE APOTHECARY</span><h2>Objects for<br><em>intentional living.</em></h2><p>A considered collection of Hapé blends and traditional applicators. Each carries its own character, story, and place in practice.</p><a class="button button-dark" href="/shop/">Enter the collection <span>↗</span></a><span class="editorial-numeral">✺</span></div></section>
<section class="collection section-wrap"><div class="section-heading"><div><p class="eyebrow">03 / HAND SELECTED</p><h2>A closer look at<br><em>the collection.</em></h2></div><a class="underline-link" href="/shop/">View the full collection <span>↗</span></a></div><div class="product-grid featured-grid">'''+''.join(card(p) for p in products[:3])+'''</div></section>
<section class="manifesto"><div class="manifesto-top"><span>THE SACRED IS NOT FAR AWAY</span><span>✺</span><span>IT BEGINS WITH ATTENTION</span></div><p>Come as you are.<br><em>Leave more connected.</em></p><a href="/offerings/">EXPLORE THE OFFERINGS ↗</a></section>
<section class="offerings-home section-wrap"><div><p class="eyebrow">04 / IN COMMUNITY</p><h2>Space to <em>come together.</em></h2><p>From Reiki and community circles to retreats and integration support, our offerings create room for reflection and connection.</p><a class="underline-link" href="/offerings/">Explore our offerings <span>↗</span></a></div><div class="offering-list"><a href="/offerings/">01 <span>Reiki & energy work</span> ↗</a><a href="/offerings/">02 <span>Community circles</span> ↗</a><a href="/offerings/">03 <span>Retreats & group journeys</span> ↗</a><a href="/offerings/">04 <span>Integration & support</span> ↗</a></div></section>
<section class="contact-banner"><div><p class="eyebrow light">A CONVERSATION IS A BEGINNING</p><h2>Find your way<br><em>back to center.</em></h2></div><a class="button button-cream" href="/contact/">Get in touch <span>↗</span></a></section>'''
write('index.html',shell('Home',home,'Home'))

about='''<section class="page-hero"><p class="eyebrow">THE PEOPLE & PURPOSE</p><h1>Rooted in connection.<br><em>Open to possibility.</em></h1><p>Our story begins with the belief that healing is a collective journey.</p></section><section class="about-content section-wrap"><div class="about-image" role="img" aria-label="Sunlight over a forest canopy"></div><div><p class="eyebrow">OUR ETHOS</p><h2>A space to feel<br><em>seen and supported.</em></h2><p>Sacred Origins NYC is a collective dedicated to empowering BIPOC communities through sacred healing practices. We recognize that personal reflection and community connection can bring us closer to the wisdom and resilience of our ancestors.</p><p>Our offerings include Reiki, Earth Medicine Ceremonies, retreats, and spaces for meaningful conversation. We welcome each person with care and respect for their individual path.</p><a class="underline-link" href="/contact/">Connect with us <span>↗</span></a></div></section><section class="values"><div class="section-wrap"><p class="eyebrow light">WHAT GUIDES US</p><div class="values-grid"><div><span>01</span><h3>Community</h3><p>We gather in a spirit of belonging, support, and shared growth.</p></div><div><span>02</span><h3>Intention</h3><p>We approach every practice with presence, care, and purpose.</p></div><div><span>03</span><h3>Respect</h3><p>We honor the roots and relationships behind these traditions.</p></div></div></div></section>'''
write('about/index.html',shell('Our Story',about,'Our Story'))

offerings=[('Reiki','Gentle energy work that creates space for quiet reflection, rest, and reconnection.'),('Kambo ceremonies','An intentional ceremonial offering rooted in Amazonian traditions. Contact us to learn about the approach and whether it is appropriate for you.'),('Retreats & group journeys','Immersive gatherings centered on community, reflection, and shared experience.'),('Hapé & Sananga circles','Community circles that approach traditional plant practices with care, intention, and respect.'),('Preparation & integration','A supportive space to reflect before and after profound personal experiences.'),('House cleansings / limpias','Intentional rituals for the spaces we live and gather in.')]
off='''<section class="page-hero"><p class="eyebrow">GATHER · REFLECT · CONNECT</p><h1>Our <em>offerings.</em></h1><p>Thoughtful spaces for reflection, community, and connection.</p></section><section class="offerings-page section-wrap"><div class="section-heading"><div><p class="eyebrow">WAYS TO CONNECT</p><h2>Find your <em>way in.</em></h2></div><p>Questions about an offering? Reach out and start a conversation.</p></div><div class="offering-cards">'''+''.join(f'<div class="offering-card"><span>{i:02d} / 06</span><h3>{n}</h3><p>{d}</p><a href="/contact/?subject={quote(n)}">Ask us about this <span>↗</span></a></div>' for i,(n,d) in enumerate(offerings,1))+'''</div></section><section class="contact-banner"><div><p class="eyebrow light">A PERSONAL CONNECTION</p><h2>Curious about<br><em>working together?</em></h2></div><a class="button button-cream" href="/contact/">Contact us <span>↗</span></a></section>'''
write('offerings/index.html',shell('Offerings',off,'Offerings'))

shop='''<section class="page-hero shop-hero"><p class="eyebrow">THE SACRED ORIGINS APOTHECARY</p><h1>Gather your <em>ritual.</em></h1><p>Hapé blends and traditional applicators, chosen for intentional practice.</p></section><section class="shop-section section-wrap"><div class="shop-top"><div><p class="eyebrow">EXPLORE THE COLLECTION</p><h2>Objects with <em>intention.</em></h2></div><div class="filters" role="group" aria-label="Filter products"><button class="filter active" data-filter="all" aria-pressed="true">All <span>05</span></button><button class="filter" data-filter="Hapé" aria-pressed="false">Hapé <span>03</span></button><button class="filter" data-filter="Applicator" aria-pressed="false">Applicators <span>02</span></button></div></div><div class="product-grid full-grid">'''+''.join(f'<div data-category="{p[2]}">{card(p)}</div>' for p in products)+'''</div><p class="shop-note">These are the five items currently shared with us. Images are editorial representations; final product photos, sizes, prices, and availability will be confirmed before orders open.</p></section>'''
write('shop/index.html',shell('Shop',shop,'Shop','Explore Sacred Origins Hapé blends, Kuripe and Tepi applicators.'))

for p in products:
    slug,name,cat,mood,desc=p
    detail=f'''<section class="detail section-wrap"><div class="detail-image product-{slug}" role="img" aria-label="Editorial representation of {escape(name)}"></div><div class="detail-copy"><a class="back-link" href="/shop/">← Back to the collection</a><p class="eyebrow">THE APOTHECARY / {escape(cat.upper())}</p><h1>{escape(name)}</h1><p class="detail-mood">{escape(mood)}</p><div class="detail-divider"></div><p>{escape(desc)}</p><div class="availability"><span>Availability & pricing</span><strong>Contact us for details</strong></div><a class="button button-dark" href="/contact/?product={slug}">Inquire about {escape(name)} <span>↗</span></a><p class="detail-footnote">Editorial imagery illustrates the collection and may differ from the final item.</p></div></section><section class="related section-wrap"><div class="section-heading"><h2>Continue <em>exploring.</em></h2><a class="underline-link" href="/shop/">Shop all <span>↗</span></a></div><div class="product-grid">{''.join(card(q) for q in products if q!=p)[:0] if False else ''.join(card(q) for q in [q for q in products if q!=p][:3])}</div></section>'''
    write(f'shop/{slug}/index.html',shell(name,detail,'Shop',desc[:155]))

contact='''<section class="page-hero"><p class="eyebrow">WE’D LOVE TO HEAR FROM YOU</p><h1>Let’s <em>connect.</em></h1><p>Questions about an offering, a product, or simply where to begin? Send a note.</p></section><section class="contact-section section-wrap"><div><p class="eyebrow">SACRED ORIGINS NYC</p><h2>Start a<br><em>conversation.</em></h2><p>We’ll be in touch as soon as we can.</p><a class="contact-email" href="mailto:sacredoriginsnyc@gmail.com">sacredoriginsnyc@gmail.com ↗</a><div class="contact-art" role="img" aria-label="Botanical apothecary still life"></div></div><form id="contact-form" class="contact-form"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" required placeholder="Full name"><label for="email">Email address *</label><input id="email" name="email" type="email" autocomplete="email" required placeholder="you@example.com"><label for="subject">What is this about?</label><select id="subject" name="subject"><option>General inquiry</option><option>Product inquiry</option><option>Offerings</option><option>Something else</option></select><label for="message">Your message *</label><textarea id="message" name="message" rows="6" required placeholder="Tell us what’s on your mind..."></textarea><button class="button button-dark" type="submit">Compose email <span>↗</span></button><p class="form-note">This opens your email app with your message. You can also email us directly above.</p></form></section>'''
write('contact/index.html',shell('Contact',contact,'Contact'))

write('assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#183126"/><circle cx="32" cy="32" r="13" fill="none" stroke="#d6b678" stroke-width="2"/><path d="M32 8v11M32 45v11M8 32h11M45 32h11M15 15l8 8m18 18 8 8m0-34-8 8M23 41l-8 8" stroke="#d6b678" stroke-width="2"/></svg>')
write('robots.txt','User-agent: *\nAllow: /\n')
print('Generated',len(list(root.rglob('*.html'))),'pages')
